---

- name: Getting entries from NSS
  ansible.builtin.getent:
    database: passwd
    key: '{{ neogo__user }}'

- name: Copy docker-compose file
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ neofs_ir__conf_dir }}/docker-compose.yml'
    dest: '{{ neogo__conf_dir }}/docker-compose.yml'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy dockerized systemd unit
  ansible.builtin.template:
    src: 'neogo_compose.service.j2'
    dest: '/etc/systemd/system/neogo{{ neogo__instance }}.service'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
