---

- name: Copy TLS key
  ansible.builtin.copy:
    src: '{{ neogo__tls_key }}'
    dest: '{{ neogo__tls_key_file }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy TLS cert
  ansible.builtin.copy:
    src: '{{ neogo__tls_cert }}'
    dest: '{{ neogo__tls_cert_file }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
