---

- name: Copy NeoGo wallet
  ansible.builtin.copy:
    src: '{{ neogo__wallet }}'
    dest: '{{ neogo__wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__wallet|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Stateroot Validator wallet
  ansible.builtin.copy:
    src: '{{ neogo__stateroot_wallet }}'
    dest: '{{ neogo__stateroot_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__stateroot_wallet|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Oracle wallet
  ansible.builtin.copy:
    src: '{{ neogo__oracle_wallet }}'
    dest: '{{ neogo__oracle_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__oracle_wallet|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Notary Service wallet
  ansible.builtin.copy:
    src: '{{ neogo__p2pnotary_wallet }}'
    dest: '{{ neogo__p2pnotary_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__p2pnotary_wallet|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
