---

- name: Copy NeoGo wallet
  ansible.builtin.copy:
    content: '{{ neogo__wallet_content | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neogo__wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__wallet_content|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Stateroot Validator wallet
  ansible.builtin.copy:
    content: '{{ neogo__stateroot_wallet_content | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neogo__stateroot_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__stateroot_wallet_content|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Oracle wallet
  ansible.builtin.copy:
    content: '{{ neogo__oracle_wallet_content | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neogo__oracle_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__oracle_wallet_content|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]

- name: Copy Notary Service wallet
  ansible.builtin.copy:
    content: '{{ neogo__p2pnotary_wallet_content | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neogo__p2pnotary_wallet_path }}'
    owner: 'root'
    group: '{{ neogo__group }}'
    mode: '0640'
  when: neogo__p2pnotary_wallet_content|length
  notify: [ 'Restart NeoGo{{ neogo__instance }}' ]
